export const LIBRARY_BOOKS = [
  // ─── ENGLISH ───────────────────────────────────────────
  {
    id: 'en-1',
    title: 'Alice in Wonderland',
    author: 'Lewis Carroll',
    genre: 'Fairy Tale',
    lang: 'en',
    content: 'Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do. Once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, and what is the use of a book, thought Alice, without pictures or conversations? So she was considering in her own mind, as well as she could, for the hot day made her feel very sleepy and stupid, whether the pleasure of making a daisy chain would be worth the trouble of getting up and picking the daisies, when suddenly a white rabbit with pink eyes ran close by her. There was nothing so very remarkable in that, nor did Alice think it so very much out of the way to hear the rabbit say to itself, "Oh dear! Oh dear! I shall be too late!" But when the rabbit actually took a watch out of its waistcoat pocket and looked at it and then hurried on, Alice started to her feet, for it flashed across her mind that she had never before seen a rabbit with either a waistcoat pocket or a watch to take out of it.',
  },
  {
    id: 'en-2',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    genre: 'Romance',
    lang: 'en',
    content: 'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters. My dear Mr. Bennet, said his lady to him one day, have you heard that Netherfield Park is let at last? Mr. Bennet replied that he had not. But it is, returned she; for Mrs. Long has just been here, and she told me all about it. Mr. Bennet made no answer. Do you not want to know who has taken it? cried his wife impatiently. You want to tell me, and I have no objection to hearing it. This was invitation enough. Why, my dear, you must know, Mrs. Long says that Netherfield is taken by a young man of large fortune from the north of England.',
  },
  {
    id: 'en-3',
    title: 'The Old Man and the Sea',
    author: 'Ernest Hemingway',
    genre: 'Adventure',
    lang: 'en',
    content: 'He was an old man who fished alone in a skiff in the Gulf Stream and he had gone eighty-four days now without taking a fish. In the first forty days a boy had been with him. But after forty days without a fish the boy\'s parents had told him that the old man was now definitely and finally salao, which is the worst form of unlucky, and the boy had gone at their orders in another boat which caught three good fish the first week. It made the boy sad to see the old man come in each day with his skiff empty and he always went down to help him carry either the coiled lines or the gaff and harpoon and the sail that was furled around the mast. The sail was patched with flour sacks and, furled, it looked like the flag of permanent defeat. The old man was thin and gaunt with deep wrinkles in the back of his neck. The brown blotches of the benevolent skin cancer the sun brings from its reflection on the tropic sea were on his cheeks.',
  },
  {
    id: 'en-4',
    title: 'The Ugly Duckling',
    author: 'Hans Christian Andersen',
    genre: 'Fairy Tale',
    lang: 'en',
    content: 'It was summer in the land, and the weather was wonderfully warm. All the mother ducks were sitting comfortably in the nest with their little ones hatched out and peeping around them. The big eggs were still unbroken. "How they do chatter, the little things," said the old duck, as one after another the tiny creatures struggled out of their shells. "How big they are! Not one like the others. Is it possible they are not ducklings at all? I will soon find out. I must make them go into the water, even if I have to push them myself." One by one they jumped into the water with a splash. The water closed over their heads, and they came up again immediately, swimming gracefully with their yellow legs, every one was there. The last great egg burst with a crack. "Oh! What a splendid big fellow!" said the old duck. "He does not look at all like the others. I wonder if he is a young turkey. Well, we shall soon find out. I must make him go into the water, even if I have to push him myself."',
  },
  {
    id: 'en-5',
    title: 'A Christmas Carol',
    author: 'Charles Dickens',
    genre: 'Holiday',
    lang: 'en',
    content: 'Marley was dead, to begin with. There is no doubt whatever about that. The register of his burial was signed by the clergyman, the clerk, the undertaker, and the chief mourner. Scrooge signed it. And Scrooge\'s name was good upon \'Change, for anything he chose to put his hand to. Old Marley was as dead as a door-nail. Mind! I don\'t mean to say that I know, of my own knowledge, what there is particularly dead about a door-nail. I might have been inclined, myself, to regard a coffin-nail as the deadest piece of ironmongery in the trade. But the wisdom of our ancestors is in the simile; and my unhallowed hands shall not disturb it, or the Country\'s done for. You will therefore permit me to repeat, emphatically, that Marley was as dead as a door-nail. Scrooge knew he was dead? Of course he did. How could it be otherwise? Scrooge and he were partners for I don\'t know how many years.',
  },
  {
    id: 'en-6',
    title: 'The Art of War',
    author: 'Sun Tzu',
    genre: 'Philosophy',
    lang: 'en',
    content: 'Sun Tzu said: The art of war is of vital importance to the State. It is a matter of life and death, a road either to safety or to ruin. Hence it is a subject of inquiry which can on no account be neglected. The art of war, then, is governed by five constant factors, to be taken into account in one\'s deliberations, when seeking to determine the conditions obtaining in the field. These are: The Moral Law, Heaven, Earth, The Commander, Method and discipline. The Moral Law causes the people to be in complete accord with their ruler, so that they will follow him regardless of their lives, undismayed by any danger. Heaven signifies night and day, cold and heat, times and seasons. Earth comprises distances, great and small, danger and security, open ground and narrow passes, the chances of life and death. The Commander stands for the virtues of wisdom, sincerity, benevolence, courage and strictness.',
  },
  {
    id: 'en-7',
    title: 'The Jungle Book',
    author: 'Rudyard Kipling',
    genre: 'Adventure',
    lang: 'en',
    content: 'Now Chil the Kite brings home the night that Mang the Bat sets free, the herds are shut in byre and hut for lost till dawn see me. This is the hour of pride and power, talon and tush and claw. Oh, hear the call, good hunting all that keep the Jungle Law! Night sings in the ears of all the Jungle that wakes and waits. In the hot still darkness of the night, the young wolf cub trembled. His mother lay beside him, one paw over her restless offspring. The jungle was alive with sound, the chatter of monkeys, the distant roar of a tiger, the soft padding of feet on the forest floor. Mowgli, the man-cub, opened his eyes and looked up at the great banyan tree overhead. Bagheera, the black panther, was somewhere in the darkness, his voice soft and reassuring. "The Pack has decided," Bagheera said quietly. "The man-cub shall be taught the Law of the Jungle."',
  },
  {
    id: 'en-8',
    title: 'The Secret Garden',
    author: 'Frances Hodgson Burnett',
    genre: 'Children',
    lang: 'en',
    content: 'When Mary Lennox was sent to Misselthwaite Manor to live with her uncle everybody said she was the most disagreeable-looking child ever seen. It was true, too. She had a little thin face and a little thin body, thin light hair and a sour expression. Her hair was yellow, and her face was yellow because she had been born in India and had always been ill in one way or another. Her father had held a position under the English Government and had always been busy and ill himself, and her mother had been a great beauty who cared only to go to parties and amuse herself with gossips. She had not wanted a little girl at all, and when Mary was born she handed her over to the care of an Ayah, who was told that she must always be kept out of the way. So Mary was rarely seen in the compound and had been sent to England.',
  },
  {
    id: 'en-9',
    title: 'The Raven',
    author: 'Edgar Allan Poe',
    genre: 'Poetry',
    lang: 'en',
    content: `Once upon a midnight dreary, while I pondered, weak and weary, over many a quaint and curious volume of forgotten lore, while I nodded, nearly napping, suddenly there came a tapping, as of someone gently rapping, rapping at my chamber door. "'Tis some visitor," I muttered, "tapping at my chamber door, only this and nothing more." Ah, distinctly I remember it was in the bleak December, and each separate dying ember wrought its ghost upon the floor. Eagerly I wished the morrow; vainly I had sought to borrow from my books surcease of sorrow, sorrow for the lost Lenore, for the rare and radiant maiden whom the angels name Lenore, nameless here for evermore. And the silken, sad, uncertain rustling of each purple curtain thrilled me, filled me with fantastic terrors never felt before; so that now, to still the beating of my heart, I stood repeating, "’Tis some visitor."`,
  },
  {
    id: 'en-10',
    title: 'The Wonderful Wizard of Oz',
    author: 'L. Frank Baum',
    genre: 'Fantasy',
    lang: 'en',
    content: 'Dorothy lived in the midst of the great Kansas prairies, with Uncle Henry, who was a farmer, and Aunt Em, who was the farmer\'s wife. Their house was small, for the lumber to build it had to be carried by wagon many miles. There were four walls, a floor and a roof, which made one room; and this room contained a rusty looking cookstove, a cupboard for the dishes, a table, three or four chairs, and the beds. Uncle Henry and Aunt Em had a big bed in one corner, and Dorothy a little bed in another corner. There was no garret at all and no cellar, except a small hole dug in the ground, called a cyclone cellar, where the family could go in case one of those great whirlwinds arose, mighty enough to crush any building in its path. It was reached by a trap door in the middle of the floor.',
  },
  {
    id: 'en-11',
    title: 'Around the World in Eighty Days',
    author: 'Jules Verne',
    genre: 'Adventure',
    lang: 'en',
    content: `Mr. Phileas Fogg lived, in 1872, at No. 7, Saville Row, Burlington Gardens, the house in which Sheridan died in 1814. He was one of the most noticeable members of the Reform Club, though he seemed always to avoid attracting attention; an enigmatic personage, about whom little else was known than that he was a polished man of the world. People said that he resembled Byron, at least that his head was Byronic; but he was a bearded, tranquil Byron, who might live on a thousand years without growing old. Certainly an Englishman, it was more doubtful whether Phileas Fogg was a Londoner. He was never seen on 'Change, nor at the Bank, nor in the counting room of any City firm. Not that he was ever known to have business connections of any kind; he had no trade or profession.`,
  },
  {
    id: 'en-12',
    title: 'The Adventures of Tom Sawyer',
    author: 'Mark Twain',
    genre: 'Adventure',
    lang: 'en',
    content: 'Tom! Tom! No response. Tom! Tom! No response. The old lady pulled her spectacles down and looked over them about the room; then she put them up and looked out under them. She seldom or never looked through them for so small a thing as a boy; they were her state pair, the pride of her heart, and were built for "style," not service; she could have seen through a pair of stove lids just as well. She looked perplexed for a moment, and then said, not fiercely, but still loud enough for the furniture to hear: "Well, I lay if I get hold of you I\'ll..." She did not finish, for by this time she was bending down and punching under the bed with the broom, and so she needed breath to punctuate the punches with. She resurrected nothing but the cat.',
  },
  {
    id: 'en-13',
    title: 'Aesop\'s Fables',
    author: 'Aesop',
    genre: 'Fable',
    lang: 'en',
    content: 'A tortoise and an eagle struck up an acquaintance. The tortoise, sensible of her own deficiency in aviation, earnestly begged the eagle to teach her to fly. She urged her request with such pathetic entreaties that the eagle at length consented. The bird took the tortoise up to a great height and, opening her claws, let her go. Down came the tortoise, crashing on the rocks below. A fox, coming by at the moment, picked her bones clean. "If you had had the sense to keep silent about what you did not understand," observed the fox, "you might have lived to a good old age. It is best not to aim at things beyond our natural powers." The Hare was always laughing at the Tortoise for being so slow. "Well, when I win the race, will you still laugh at me?" asked the Tortoise. The Hare agreed, and they set off. The Tortoise went steadily on, step by step, while the Hare, overconfident, fell asleep.',
  },
  {
    id: 'en-14',
    title: 'Treasure Island',
    author: 'Robert Louis Stevenson',
    genre: 'Adventure',
    lang: 'en',
    content: 'Squire Trelawney, Dr. Livesey, and the rest of these gentlemen having asked me to write down the whole particulars about Treasure Island, from the beginning to the end, keeping nothing back but the bearings of the island, and that only because there is still treasure not yet lifted, I take up my pen in the year of grace 17__, and go back to the time when my father kept the Admiral Benbow inn, and the brown old seaman with the sabre cut first took up his lodging under our roof. I remember him as if it were yesterday, as he came plodding to the inn door, his sea-chest following behind him in a hand-barrow, a tall, strong, heavy, nut-brown man, his tarry pigtail falling over the shoulder of his soiled blue coat, his hands ragged and scarred, with black, broken nails, and the sabre cut across one cheek, a dirty, livid white.',
  },
  {
    id: 'en-15',
    title: 'The Odyssey',
    author: 'Homer',
    genre: 'Mythology',
    lang: 'en',
    content: 'Tell me, O Muse, of that ingenious hero who travelled far and wide after he had sacked the famous town of Troy. Many cities did he visit, and many were the nations with whose manners and customs he was acquainted; moreover he suffered much by sea while trying to save his own life and bring his men safely home; but do what he might he could not save his men, for they perished through their own sheer folly in eating the cattle of the Sun-god Hyperion; so the god prevented them from ever reaching home. Tell me, too, about all these things, O daughter of Jove, from whatever quarter you may have heard them. The hero himself, Odysseus, had a rough time of it after he had sacked Troy. All his companions were dead; he was their sole survivor.',
  },
  {
    id: 'en-16',
    title: 'The Little Prince',
    author: 'Antoine de Saint-Exupery',
    genre: 'Fairy Tale',
    lang: 'en',
    content: 'When I was six years old I once saw a magnificent picture in a book on the virgin forest called True Stories. It represented a boa constrictor swallowing an animal. In the book it said: "Boa constrictors swallow their prey whole, without chewing it. After that they are not able to move, and they sleep for six months for their digestion." I thought a lot about the adventures of the jungle and, in my turn, I made my first drawing with a crayon. My drawing Number One looked like this. I showed my masterpiece to the grown-ups and asked them whether my drawing frightened them. But they answered: "Frighten? Why should anyone be frightened by a hat?" My drawing was not a picture of a hat. It was a picture of a boa constrictor digesting an elephant. Since the grown-ups were not able to understand it, I made another drawing: I drew the inside of the boa constrictor, so that the grown-ups could see it clearly.',
  },
  {
    id: 'en-17',
    title: 'The War of the Worlds',
    author: 'H.G. Wells',
    genre: 'Science Fiction',
    lang: 'en',
    content: 'No one would have believed in the last years of the nineteenth century that this world was being watched keenly and closely by intelligences greater than man\'s and yet as mortal as his own; that as men busied themselves about their various concerns they were scrutinised and studied, perhaps almost as narrowly as a man with a microscope might scrutinise the transient creatures that swarm and multiply in a drop of water. With infinite complacency men went to and fro over this globe about their little affairs, serene in their assurance of their empire over matter. It is possible that the infusoria under the microscope do the same. No one gave a thought to the older worlds of space as sources of human danger, or thought of them only to dismiss the idea of life upon them as impossible or improbable.',
  },
  {
    id: 'en-18',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    genre: 'Gothic',
    lang: 'en',
    content: 'You will rejoice to hear that no disaster has accompanied the commencement of an enterprise which you have regarded with such evil forebodings. I arrived here yesterday, and my first task is to assure my dear sister of my welfare and increasing confidence in the success of my undertaking. I am already far north of London, and as I walk in the streets of Petersburgh, I feel a cold northern breeze play upon my cheeks, which braces my nerves and fills me with delight. Do you understand this feeling? This breeze, which has travelled from the regions towards which I am advancing, gives me a foretaste of those icy climes. Inspirited by this wind of promise, my daydreams become more fervent and vivid.',
  },
  {
    id: 'en-19',
    title: 'Moby Dick',
    author: 'Herman Melville',
    genre: 'Adventure',
    lang: 'en',
    content: 'Call me Ishmael. Some years ago, never mind how long precisely, having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world. It is a way I have of driving off the spleen and regulating the circulation. Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people\'s hats off, then, I account it high time to get to sea as soon as I can.',
  },
  {
    id: 'en-20',
    title: 'The Time Machine',
    author: 'H.G. Wells',
    genre: 'Science Fiction',
    lang: 'en',
    content: 'The Time Traveller, for so it will be convenient to speak of him, was expounding a recondite matter to us. His pale grey eyes were shining and animated, and he had that happy manner of a man who has been the subject of an experiment that has succeeded. He sat before us in his leather armchair, and the faint aroma of oil from the machine still lingering in the air. The speculations he had made upon the possibility of time travel had seemed fantastic, yet here was the proof before our very eyes. "I can assure you," he said, leaning forward with eagerness, "that the fourth dimension is not merely a mathematical concept. It is a real direction in which one can move, just as one moves in the three dimensions of length, breadth, and thickness. I have been there and back." We exchanged skeptical glances.',
  },

  // ─── MALAY ─────────────────────────────────────────────
  {
    id: 'ms-1',
    title: 'Malin Kundang',
    author: 'Cerita Rakyat',
    genre: 'Folklore',
    lang: 'ms',
    content: 'Pada suatu masa dahulu, di sebuah desa di tepi laut, hiduplah seorang janda miskin bernama Pak Mandar bersama anak tunggalnya, Malin Kundang. Malin Kundang adalah seorang anak yang rajin membantu ibunya. Setiap hari, dia pergi ke laut untuk mencari ikan bagi menyara hidup mereka berdua. Suatu hari, sebuah kapal besar berlabuh di pantai berhampiran desa mereka. Nakhoda kapal itu terkesan dengan keuletan Malin Kundang dan menawarkannya untuk bekerja di kapal. Dengan berat hati, Malin Kundang meninggalkan ibunya untuk mencari nasib di laut. Beberapa tahun kemudian, Malin Kundang telah menjadi seorang saudagar yang kaya raya. Dia berkahwin dengan anak seorang raja dan hidup mewah. Suatu hari, kapal Malin Kundang berlabuh di kampung halamannya. Namun, apabila melihat ibunya yang tua dan miskin berjalan ke arahnya, Malin Kundang malu dan menafikan bahawa wanita itu adalah ibunya.',
  },
  {
    id: 'ms-2',
    title: 'Hang Tuah',
    author: 'Hikayat Hang Tuah',
    genre: 'Epic',
    lang: 'ms',
    content: 'Alkisah maka berlayarlah Hang Tuah dan kawan-kawannya menghadap ke laut lepas. Maka apabila sampai di tengah-tengah laut, maka berkata Hang Tuah kepada kawan-kawannya: "Saudara-saudaraku sekalian, baiklah kita berpisah di sini. Masing-masing pergilah mencari nasib sendiri." Maka berpisahlah mereka berlima. Hang Tuah belayar ke negeri seberang, manakala Hang Jebat tinggal di Melaka. Beberapa lama kemudian, Hang Tuah kembali ke Melaka setelah menjadi terkenal di negeri-negeri asing. Baginda Sultan terlalu gembira menerima kembali hamba setianya itu dan mengangkatnya menjadi Bendahara. Namun, nasib tidak selalu berpihak kepada yang baik. Hang Tuah difitnah oleh musuh-musuhnya dan dibuang negeri oleh Sultan. Hatinya pilu, tetapi kesetiaannya kepada Sultan tidak pernah berubah.',
  },
  {
    id: 'ms-3',
    title: 'Sang Kancil dan Buaya',
    author: 'Cerita Rakyat',
    genre: 'Folklore',
    lang: 'ms',
    content: 'Pada suatu hari yang panas, Sang Kancil yang licik sedang berjalan di tepi sungai. Dia sangat haus dan ingin minum air sungai yang jernih itu. Namun, dia tahu bahawa di dalam sungai itu terdapat banyak buaya yang lapar. Sang Kancil berfikir sejenak dan akhirnya mempunyai satu idea yang bijak. "Hai, saudara-saudara buaya!" seru Sang Kancil dengan suara yang kuat. "Raja telah mengarahkan saya mengira berapa banyak buaya yang ada di sungai ini untuk membuat perbarisan besar-besaran." Para buaya terpesona dengan berita itu dan beratur satu persatu dari satu hujung sungai ke hujung yang lain. Sang Kancil dengan selamba melompat dari belakang buaya yang satu ke buaya yang lain, sambil mengira dengan kuat. Apabila sampai ke seberang sungai, Sang Kancil terus berlari masuk ke dalam hutan sambil tertawa kecil.',
  },
  {
    id: 'ms-4',
    title: 'Puteri Gunung Ledang',
    author: 'Cerita Rakyat',
    genre: 'Legend',
    lang: 'ms',
    content: 'Di zaman pemerintahan Sultan Mahmud Shah, terdapat khabar angin yang mengatakan bahawa Puteri Gunung Ledang, seorang puteri yang cantik jelita, tinggal di puncak gunung itu. Sultan Mahmud Shah, yang terpesona dengan kecantikan puteri itu, menghantar beberapa orang hulubalang untuk melamar puteri tersebut. Baginda menawarkan pelbagai hadiah yang mahal, termasuk emas, permata, dan kain sutera. Namun, puteri itu menolak setiap lamaran dengan syarat-syarat yang mustahil dipenuhi. Dia meminta tali yang diperbuat daripada akar pokok bunga tanjung, air mata anak ayam jantan, dan piring yang diperbuat daripada tanah dasar laut. Setiap syarat itu jelas tidak mungkin dipenuhi oleh sesiapa pun.',
  },
  {
    id: 'ms-5',
    title: 'Cincin Seribu Naga',
    author: 'Cerita Rakyat',
    genre: 'Fantasy',
    lang: 'ms',
    content: 'Di sebuah kerajaan yang jauh di seberang lautan, hiduplah seorang puteri yang bijaksana dan baik hati. Puteri itu mempunyai sebuah cincin ajaib yang dipercayai mengandungi kuasa seribu naga. Cincin itu diwarisi turun-temurun dalam keluarganya sejak beratus-ratus tahun lamanya. Pada suatu hari, kerajaan itu diserang oleh tentera penjahat yang ingin merampas cincin ajaib itu. Puteri itu nekad untuk mempertahankan cincin tersebut kerana dia tahu bahawa jika jatuh ke tangan yang salah, kuasa itu boleh memusnahkan seluruh dunia. Dengan bantuan cincin itu, puteri itu memanggil seekor naga yang besar dan kuat. Naga itu membantu puteri menghalau tentera penjahat dari kerajaan mereka. Sejak hari itu, puteri itu menjaga cincin itu dengan lebih berhati-hati.',
  },
  {
    id: 'ms-6',
    title: 'Si Tanggang',
    author: 'Cerita Rakyat',
    genre: 'Folklore',
    lang: 'ms',
    content: 'Si Tanggang adalah seorang pemuda yang durhaka kepada ibunya. Setelah berkahwin dengan anak orang kaya, dia malu untuk mengakui ibunya yang miskin. Pada suatu hari, apabila ibunya datang ke rumahnya untuk menjenguk, Si Tanggang menolaknya dan berkata: "Pergilah dari sini! Aku tidak mengenali engkau!" Sang ibu yang hancur hatinya berdoa dengan penuh keikhlasan. "Ya Tuhan, jika ini benar anakku yang durhaka, biarlah dia menjadi batu!" Tiba-tiba, langit menjadi gelap dan petir menyambar. Si Tanggang berubah menjadi sebuah batu yang terletak di tepi laut. Sehingga hari ini, orang ramai masih boleh melihat batu itu dan mengingati kisah tentang anak yang durhaka kepada ibunya. Ibu yang telah meninggal dunia itu tidak pernah memaafkan Si Tanggang, kerana dosa anak yang melupakan jasa ibu adalah dosa yang tidak terampuni.',
  },
  {
    id: 'ms-7',
    title: 'Nakhoda Hayat',
    author: 'Hikayat',
    genre: 'Adventure',
    lang: 'ms',
    content: 'Nakhoda Hayat adalah seorang pelaut yang terkenal di kepulauan Melayu. Dia mengemudi kapalnya ke serata lautan untuk berniaga. Suatu hari, kapalnya karam akibat ribut besar di tengah laut. Hayat terapung-apung di atas air selama tiga hari tiga malam sehingga terdampar di sebuah pulau yang tidak dikenali. Di pulau itu, Hayat menemui sebuah gua yang penuh dengan harta karun. Terdapat emas, permata, dan barangan berharga yang tidak terhitung banyaknya. Namun, Hayat sedar bahawa harta itu tidak berguna jika dia tidak dapat pulang ke kampung halamannya. Dia membina sebuah rakit kecil daripada kayu yang terapung dan belayar selama berhari-hari sehingga akhirnya terselamat. Hayat kembali ke kampungnya dengan membawa sedikit harta karun untuk berkongsi dengan penduduk kampung.',
  },
  {
    id: 'ms-8',
    title: 'Pelanduk Semarak',
    author: 'Cerita Rakyat',
    genre: 'Folklore',
    lang: 'ms',
    content: 'Pelanduk Semarak adalah seekor pelanduk yang sangat cantik dan lincah. Dia tinggal di dalam hutan yang tebal bersama keluarganya. Suatu hari, Pelanduk Semarak tersesat semasa mencari makanan. Dia berjalan jauh sehingga terkeluar dari hutan dan masuk ke kawasan kebun penduduk kampung. Penduduk kampung terpegun dengan keindahan bulu pelanduk itu. Mereka berpendapat bahawa Pelanduk Semarak terlalu cantik untuk dibiar hidup liar. Mereka menangkap Pelanduk Semarak dan memeliharanya dalam sangkar emas. Namun, Pelanduk Semarak tidak gembira walaupun diberi makanan yang lazat. Dia merindui hutan dan keluarganya. Akhirnya, dengan bantuan burung-burung di hutan, Pelanduk Semarak berjaya melarikan diri dan pulang ke rumah.',
  },
  {
    id: 'ms-9',
    title: 'Bawang Putih dan Bawang Merah',
    author: 'Cerita Rakyat',
    genre: 'Fairy Tale',
    lang: 'ms',
    content: 'Dahulu kala, ada dua orang adik-beradik bernama Bawang Putih dan Bawang Merah. Bawang Putih adalah anak yang baik hati dan rajin, manakala Bawang Merah pula pemalas dan suka membuli. Ibu Bawang Merah selalu menganiaya Bawang Putih dengan memberikannya kerja yang berat-berat. Suatu hari, Bawang Putih diminta mencuci baju di sungai. Semasa mencuci, sehelai kain putih milik puteri raja hanyut ke tangannya. Bawang Putih mengikut kain itu sehingga ke istana. Puteri raja terkesan dengan kebaikan Bawang Putih dan mengambilnya sebagai anak angkat. Sejak itu, Bawang Putih hidup bahagia di istana. Suatu hari, Bawang Merah dan ibunya datang ke istana untuk meminta harta. Namun, kerana tamak dan jahat, mereka dihukum oleh puteri raja.',
  },
  {
    id: 'ms-10',
    title: 'Langsuir',
    author: 'Cerita Rakyat',
    genre: 'Legend',
    lang: 'ms',
    content: 'Langsuir adalah makhluk dalam mitologi Melayu yang dahulunya seorang perempuan cantik. Kononnya, semasa dia melahirkan anak, dia meninggal dunia sebelum sempat mengambil tali pusat bayinya. Jiwa yang tidak tenang itu bangkit semula sebagai langsuir, iaitu roh perempuan yang terapung-apung di udara dengan rambut panjang yang menjuntai. Langsuir dipercayai akan mengganggu manusia pada waktu malam, terutamanya di kawasan hutan dan kampung yang sunyi. Orang-orang tua dahulu akan menggantungkan perancah di pokok-pokok besar untuk melindungi diri daripada gangguan langsuir. Untuk mengusir langsuir, mereka akan meletakkan gunting atau benda tajam di bawah bantal. Hingga kini, kisah langsuir masih menjadi cerita seram yang diceritakan kepada anak-anak untuk mengingatkan mereka supaya tidak keluar rumah pada waktu malam.',
  },
  {
    id: 'ms-11',
    title: 'Hikayat Seri Rama',
    author: 'Hikayat',
    genre: 'Epic',
    lang: 'ms',
    content: 'Alkisah maka tersebutlah perkataan Seri Rama, seorang putera raja yang gagah perkasa. Dia telah berkahwin dengan puteri yang cantik bernama Siti Dewi. Namun, Siti Dewi telah diculik oleh raksasa bernama Rawana dan dibawa ke negeri Langkapuri. Seri Rama yang bersedih hati mengerahkan seluruh kekuatannya untuk menyelamatkan isterinya. Dengan bantuan kera-kera ajaib, dia membina sebuah jambatan besar untuk menyeberangi lautan. Tentera Seri Rama bertempur dengan tentera Rawana dalam peperangan yang dahsyat. Akhirnya, Seri Rama berjaya menewaskan Rawana dan menyelamatkan Siti Dewi. Mereka pulang ke negara asal dengan penuh kegembiraan. Seri Rama memerintah kerajaan dengan adil dan bijaksana selama bertahun-tahun lamanya.',
  },
  {
    id: 'ms-12',
    title: 'Raja Bersiong',
    author: 'Cerita Rakyat',
    genre: 'Legend',
    lang: 'ms',
    content: 'Raja Bersiong ialah nama yang diberikan kepada seorang raja yang kejam dan suka meminum darah manusia. Kononnya, raja itu mendapati bahawa darah manusia memberikannya kekuatan dan umur yang panjang. Oleh itu, dia mula membunuh rakyatnya sendiri untuk mendapatkan darah. Rakyat-rakyatnya hidup dalam ketakutan dan kesengsaraan. Setiap malam, raja itu akan memanggil beberapa orang rakyat untuk dibawa ke istana dan tidak pernah kembali. Seorang pemuda bernama Badang, yang kehilangan isterinya akibat kekejaman raja, nekad untuk menentang raja itu. Dengan kekuatan ajaib yang diperoleh daripada roh isterinya, Badang berjaya membunuh Raja Bersiong. Sejak itu, rakyat kembali hidup aman dan damai.',
  },
  {
    id: 'ms-13',
    title: 'Nenek Titi Kerbau',
    author: 'Cerita Rakyat',
    genre: 'Folklore',
    lang: 'ms',
    content: 'Nenek Titi Kerbau tinggal di sebuah kampung kecil di tepi sungai. Dia adalah seorang yang sangat pemurah dan suka menolong orang. Setiap hari, Nenek Titi Kerbau akan membawa kerbau kecilnya ke sungai untuk minum air. Kerbau kecil itu adalah satu-satunya harta yang dia miliki. Suatu hari, seorang budak lelaki jatuh ke dalam sungai. Nenek Titi Kerbau dengan pantas melompat ke dalam air dan berjaya menyelamatkan budak itu. Namun, semasa menyelamatkan budak itu, kerbau kecilnya hanyut dibawa arus. Nenek Titi Kerbau tidak menyesal kerana dia percaya bahawa menyelamatkan nyawa manusia lebih berharga daripada harta benda. Penduduk kampung sangat terharu dengan pengorbanan Nenek Titi Kerbau dan mengumpulkan wang untuk membeli seekor kerbau baru untuknya.',
  },
  {
    id: 'ms-14',
    title: 'Sang Kelembai',
    author: 'Cerita Rakyat',
    genre: 'Mythology',
    lang: 'ms',
    content: 'Sang Kelembai ialah makhluk ajaib dalam mitologi Melayu yang mempunyai kuasa untuk menghidupkan dan mematikan sesuatu dengan hanya menyebut namanya. Dia tinggal di dalam gua yang gelap dan sunyi. Kononnya, Sang Kelembai mempunyai rupa yang sangat menakutkan, dengan tubuh yang besar dan suara yang bergemuruh seperti petir. Penduduk kampung percaya bahawa Sang Kelembai mempunyai kuasa untuk mengubah bentuk sesuatu menjadi batu. Pada suatu hari, seorang pemuda yang berani masuk ke dalam gua Sang Kelembai untuk membuktikan bahawa makhluk itu tidak wujud. Apabila pemuda itu bertemu dengan Sang Kelembai, dia terkejut dengan kuasa makhluk itu. Sang Kelembai mengarahkan pemuda itu keluar dari gua dan memberi amaran supaya tidak menceritakan tentang pertemuan itu kepada sesiapa.',
  },
  {
    id: 'ms-15',
    title: 'Singapura Dilanggar Todak',
    author: 'Sejarah',
    genre: 'Historical',
    lang: 'ms',
    content: 'Pada suatu masa dahulu, apabila Singapura masih merupakan sebuah kota kecil yang diperintah oleh Temenggong, laut di sekitar pulau itu diganggu oleh sekumpulan todak yang besar-besar. Todak-todak itu menyerang penduduk yang berada di pantai dan mengoyakkan tubuh mereka dengan paruh yang tajam. Penduduk Singapura hidup dalam ketakutan kerana serangan todak itu semakin kerap berlaku. Temenggong, yang tidak tahan melihat rakyatnya menderita, mengadakan satu perjumpaan besar untuk membincangkan cara menghalau todak itu. Seorang kanak-kanak bijak bernama Hang Jebat mencadangkan agar setiap rumah diberikan sebatang lidi kelapa untuk dijadikan senjata. Apabila todak menyerang, penduduk akan menusuk todak dengan lidi itu. Cadangan itu diterima dan dilaksanakan. Apabila todak menyerang lagi, penduduk berjaya menghalau mereka dengan lidi-lidi itu.',
  },
  {
    id: 'ms-16',
    title: 'Tahi Bintang',
    author: 'Puisi',
    genre: 'Poetry',
    lang: 'ms',
    content: 'Di langit yang luas terbentang, bintang-bintang berkerlipan bagai mutiara yang bersinar. Aku memandang ke atas dan terpesona dengan keindahan alam semesta ini. Setiap bintang mempunyai ceritanya sendiri, seperti kita manusia di bumi. Ada yang terang benderang, ada yang redup, tetapi semua itu menyumbang kepada keindahan malam. Kita tidak perlu menjadi bintang yang paling terang untuk memberi makna. Kadang-kadang, cahaya yang kecil dan lemah itu cukup untuk membimbing seseorang yang sesat di dalam gelap. Itulah keindahan kehidupan, setiap kita mempunyai peranan masing-masing. Jangan sesekali memandang rendah pada kebolehan diri sendiri kerana Tuhan tidak menjadikan sesuatu itu sia-sia. Teruslah bersinar walaupun dunia tidak memandang. Bintang tidak pernah meminta perhatian, tetapi cahayanya tetap menerangi malam.',
  },
  {
    id: 'ms-17',
    title: 'Cerita Si Kancil',
    author: 'Cerita Rakyat',
    genre: 'Fable',
    lang: 'ms',
    content: 'Si Kancil, si kancil comel, selalu berjalan dengan langkah yang ringan di dalam hutan. Dia terkenal dengan kecerdikannya yang luar biasa. Setiap kali menghadapi masalah, Si Kancil akan berfikir dengan teliti sebelum bertindak. Suatu hari, Si Kancil terjatuh ke dalam perigi yang dalam. Dia berteriak minta tolong. Kancil-kancil lain di hutan datang untuk menolong, tetapi perigi itu terlalu dalam untuk mereka capai. Si Kancil memikirkan sesuatu yang bijak. Dia berkata, "Tarik saya dengan ekor saya!" Kancil-kancil lain berpendapat itu idea yang pelik, tetapi mereka mencubanya. Apabila mereka menarik ekornya, Si Kancil terlekat semakin dalam. "Bukan begitu!" kata Si Kancil. "Masukkan saya ke dalam perigi supaya saya boleh berenang naik sendiri!" Kancil-kancil lain bingung, tetapi mereka melakukannya. Apabila air perigi naik, Si Kancil mudah berenang ke atas.',
  },
  {
    id: 'ms-18',
    title: 'Hikayat Merong Mahawangsa',
    author: 'Hikayat',
    genre: 'Epic',
    lang: 'ms',
    content: 'Alkisah maka tersebutlah perkataan Merong Mahawangsa, seorang putera dari Rom yang telah berkahwin dengan puteri dari Langkasuka. Mereka mempunyai seorang anak yang diberi nama Raja Gelanggang. Merong Mahawangsa membawa keluarganya berlayar ke timur untuk mencari tanah baru. Semasa dalam perjalanan, mereka terpaksa berhadapan dengan pelbagai dugaan, termasuk ribut dahsyat dan serangan lanun. Namun, dengan keberanian dan kebijaksanaan mereka, mereka berjaya mengatasi segala halangan. Akhirnya, mereka tiba di sebuah tanah yang subur dan indah. Merong Mahawangsa menubuhkan sebuah kerajaan di sana dan memerintah dengan adil. Rakyatnya hidup aman dan makmur di bawah pemerintahannya yang bijaksana.',
  },
  {
    id: 'ms-19',
    title: 'Lagenda Tasik Chini',
    author: 'Cerita Rakyat',
    genre: 'Legend',
    lang: 'ms',
    content: 'Tasik Chini terletak di negeri Pahang dan dipercayai menjadi tempat tinggal naga yang bernama Sri Gumum. Penduduk asli di kawasan itu, iaitu suku Jakun, percaya bahawa naga itu akan muncul dari tasik pada waktu-waktu tertentu. Kononnya, tasik itu juga merupakan laluan ke sebuah negeri emas yang hilang di dasar tasik. Pada zaman dahulu, ramai pelayar dan pedagang datang ke Tasik Chini untuk mencari harta karun. Namun, tidak ada sesiapa yang pernah menemui negeri emas itu. Penduduk kampung percaya bahawa negeri emas itu hanya akan muncul kepada orang yang bersih hatinya dan tidak tamak. Tasik Chini kini menjadi tapak warisan negara yang dilindungi kerana keindahan semula jadinya yang luar biasa.',
  },
  {
    id: 'ms-20',
    title: 'Puteri Santubong dan Sejinjang',
    author: 'Cerita Rakyat',
    genre: 'Legend',
    lang: 'ms',
    content: 'Puteri Santubong dan Puteri Sejinjang ialah dua orang puteri dari kayangan yang diturunkan ke bumi untuk menjaga keamanan dunia. Mereka ditugaskan untuk membina sebuah sungai yang menghubungkan laut dengan daratan. Namun, semasa dalam proses pembinaan, mereka bertengkar kerana berbeza pendapat tentang hala tuju sungai itu. Pertengkaran itu menyebabkan berlakunya perang yang dahsyat antara mereka berdua. Pertempuran itu mengakibatkan berlakunya banjir besar yang memusnahkan banyak kampung dan membunuh ramai penduduk. Melihat kesan kemusnahan itu, raja langit murka dan menghukum kedua-dua puteri itu dengan mengubah mereka menjadi gunung. Puteri Santubong menjadi Gunung Santubong, manakala Puteri Sejinjang menjadi Pulau Sejinjang.',
  },
];

export default LIBRARY_BOOKS;
